@startuml  design3.png
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User
boundary MenuView
control MenuPresenter
control NoteService
control NoteController
control NoteServiceImpl
entity NoteRepository
entity UserRepository
database Database 

box "NSheets Client"
participant MenuView
participant MenuPresenter 
end box

box "Server"
participant NoteServiceImpl
participant NoteController
participant NoteService
participant UserRepository
participant NoteRepository
end box

box "Database"
participant Database
end box

User -> MenuPresenter : onClick() / When clicking the confirm in edit button
MenuPresenter ->> NoteServiceImpl: addVersion(NoteDTO note)
NoteServiceImpl -> NoteController : addVersion(NoteDTO note)
NoteController -> NoteService: addVersion(NoteDTO note)
NoteService -> UserRepository: getUserByUsername(Username username)
NoteService -> NoteRepository: getNotesByUser(User user)
NoteService -> NoteRepository: addVersion(NoteDTO note)
NoteRepository -> Database : delete
NoteController ->> MenuPresenter : onSuccess() 
MenuPresenter -> MenuView : refreshNotes() / Informs of success

@enduml