@startuml dm.png
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

hide empty methods
interface ExpressionCompiler

class LanguageManager {
    +getAllMacroLanguages()
}
class MacroLanguage extends Language {
    
}

class VisualBasicLanguage extends MacroLanguage

class MacroCompilerManager {
    -instance
    -compilers
    -MacroCompilerManager()
    -initCompilers()
    {static}-getInstance()
    +getCompiler(String language)
    +getCompiler(MacroLanguage lang)
}

class VisualBasicExpressionCompiler extends ExpressionCompiler

LanguageManager o-- Language : has
MacroCompilerManager o-- ExpressionCompiler : has

@enduml