@startuml  design.png
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false


actor User
boundary WorkbookView
control WorkbookView
control GWT
control AsyncCallback

box "NSheets Client"
participant WorkbookView
end box

box "Server"
participant SearchServiceImpl
end box

box "NSheets shared"
participant SearchServiceAsync
participant SearchController
participant SearchByRegularExpression

end box

box "OTHER"
participant GWT
participant AsyncCallback
end box

User -> WorkbookView : click search button
WorkbookView -> GWT : create(SearchService.class)
WorkbookView -> AsyncCallback : create()
WorkbookView -> SearchServiceImpl : showOutputOfSearch(expression, workbook, spreadsheetIndex)
SearchServiceImpl -> SearchController : create(expression, workbook, spreadsheetIndex)
SearchServiceImpl -> SearchController : showOutputOfSearch()
SearchController -> SearchByRegularExpression : search(expression, workbook, spreadsheetIndex)
WorkbookView -> User : show output in text area

@enduml