@startuml  design1.png
skinparam handwritten false
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User
boundary MenuView
control TaskPresenter
boundary TaskView
control TaskController
control TaskService
control TaskServiceImpl
entity Task
entity TaskRepository
database Database

box "NSheets Client"
participant MenuView
participant TaskPresenter
participant TaskView
end box

box "Shared"
participant TaskService
participant TaskServiceImpl
end box

box "Server"
participant Task
participant TaskController
participant TaskRepository
end box

box "Database"
participant Database
end box

User -> MenuView : open Task sub-menu
MenuView --> TaskPresenter : open()
TaskPresenter --> TaskView : openView()
TaskView -> TaskServiceImpl : getAllTasks()
TaskServiceImpl -> TaskController : getAllTasks()
TaskController -> TaskRepository : PersistenceContext.repositories().tasks()
TaskController -> TaskRepository : repo.findAll()
TaskRepository -> Database : findAll()
TaskServiceImpl -> Task : toDTO(List<Task>)
TaskView --> User : display list of Tasks
User -> TaskView : select task 
TaskView -> TaskServiceImpl : removeTask(taskDTO)
TaskServiceImpl -> Task : taskToRemove.ftomDTO(taskDTO)
TaskServiceImpl -> TaskController : removeTask(taskToRemove)
TaskController -> TaskRepository : PersistenceContext.repositories().tasks()
TaskController -> TaskRepository : repo.remove(taskToRemove)
TaskRepository -> Database : remove(taskToRemove)

alt Compilation Sucess
TaskRepository --> TaskPresenter : onSuccess
TaskPresenter --> User : Uc success scenario
else Compilation Failure
TaskRepository --> TaskPresenter : onFailure
TaskPresenter --> User : Uc failure scenario
end

@enduml