@startuml

actor User

User->System : Chooses to create a new account
System --> User : Opens the SignUp User Interface

User->System : Inputs the required data
System -> System : Validates the inserted data
System --> User: Shows the user the success of the operation
@enduml
