@startuml  analysis3.png
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User

User -> Browser : open ChartWizzard page

Server -> Browser : load Charts

User -> Browser : chooses chart

Browser -> User : shows Chart

User -> Browser : clicks to the delete Chart

Browser -> Server : deletes chart

database Database

Server -> Database : deletes chart

Browser -> User : updates list and page

@enduml