@startuml  analysis3.png
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User

User -> Browser : start use case
Browser ->> User : list calendars
User ->> Browser : select one calendar for filter
Browser ->> User : filter calendar
User ->> Browser :confirm
Browser ->> User : close window


@enduml
